theme: jekyll-theme-cayman
plugins:
  - jekyll-readme-index
title: androidsrc.dev
description: This pages aims to help developers find the Android sources they're looking for.
show_downloads: false
google_analytics: UA-142834539-2
